name: "publish"
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install frontend dependencies    
        run: yarn install

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__-alpha # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "Svara v__VERSION__-alpha"
          releaseBody: |
            Please refer to [the contribution guidelines](https://github.com/setoelkahfi/svara/blob/master/CONTRIBUTING.md#submitting-issues) for info on submitting bug reports.
            
            ### *Will have bugs/missing/incomplete features.*
          releaseDraft: true
          prerelease: true
          includeDebug: true
